services:
  - type: web
    name: authentication-appdev
    env: python
    buildCommand: poetry install && poetry run python manage.py migrate && poetry run python manage.py collectstatic --noinput
    startCommand: poetry run gunicorn backend.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: PYTHON_VERSION
        value: 3.11.11
