services:
  - type: web
    name: authentication-appdev
    runtime: python
    buildCommand: |
      cd backend
      poetry install
      poetry run python manage.py migrate
    startCommand: cd backend && poetry run gunicorn backend.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: your-database-name
          property: connectionString
      - key: SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: False
