services:
  - type: web
    name: backend
    env: python
    buildCommand: "poetry install"
    startCommand: "poetry run python backend/manage.py runserver 0.0.0.0:8000"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
